import React, { useState } from 'react';
import { BladeOffsetRow, RadialSectionGeometry } from '../../types/propeller';
import { Download, FileCode, Table, Check, Copy } from 'lucide-react';

interface PropellerOffsetTableProps {
  offsetRows: BladeOffsetRow[];
  radialGeometry: RadialSectionGeometry[];
  diameterM: number;
}

export const PropellerOffsetTable: React.FC<PropellerOffsetTableProps> = ({
  offsetRows,
  radialGeometry,
  diameterM,
}) => {
  const [selectedRadialFilter, setSelectedRadialFilter] = useState<number | 'all'>('all');
  const [copiedGcode, setCopiedGcode] = useState(false);

  const filteredRows =
    selectedRadialFilter === 'all'
      ? offsetRows
      : offsetRows.filter((r) => Math.abs(r.rRatio - selectedRadialFilter) < 0.02);

  // Generate CNC G-Code snippet
  const generateGCode = () => {
    let gcode = `( PROPELLER CNC MACHINING TOOL PATH G-CODE )\n`;
    gcode += `( DIAMETER: ${diameterM} m | GENERATED BY AI MARITIME PROPEL )\n`;
    gcode += `G21 (Metric Units mm)\nG90 (Absolute Positioning)\nG17 (XY Plane Select)\nS3500 M03 (Spindle On 3500 RPM)\n\n`;

    radialGeometry.forEach((sec) => {
      gcode += `( --- SECTION r/R = ${sec.rRatio} | CHORD ${sec.chordMm} mm --- )\n`;
      gcode += `G00 Z${(sec.rakeMm + 50).toFixed(1)}\n`;
      gcode += `G01 X${sec.chordMm.toFixed(1)} Y${sec.thicknessMm.toFixed(1)} F1200\n`;
    });
    gcode += `\nM05 (Spindle Stop)\nM30 (Program End)\n`;
    return gcode;
  };

  const handleCopyGCode = () => {
    navigator.clipboard.writeText(generateGCode());
    setCopiedGcode(true);
    setTimeout(() => setCopiedGcode(false), 2000);
  };

  const handleDownloadCsv = () => {
    let csv = `r/R,Chord_Percent,x_mm,y_Face_mm,z_Face_mm,y_Back_mm,z_Back_mm\n`;
    offsetRows.forEach((r) => {
      csv += `${r.rRatio},${r.chordPercent},${r.xMm},${r.yFaceMm},${r.zFaceMm},${r.yBackMm},${r.zBackMm}\n`;
    });
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Propeller_CNC_Offsets_${diameterM}m.csv`;
    link.click();
  };

  return (
    <div className="bg-slate-900 p-6 rounded-3xl border border-slate-800 space-y-6 text-slate-100">
      {/* Header & Export Actions */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <h2 className="text-xl font-black text-white flex items-center gap-2">
            <Table className="w-6 h-6 text-cyan-400" />
            Manufacturing Blade Offset Table & CNC Tool Paths
          </h2>
          <p className="text-slate-400 text-xs mt-1">
            Exact 3D Coordinates (X, Y, Z) for Hydrofoil Pressure Face and Suction Back for CNC Machining & Pattern Making.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleCopyGCode}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs border border-slate-700 transition"
          >
            {copiedGcode ? <Check className="w-4 h-4 text-emerald-400" /> : <FileCode className="w-4 h-4 text-cyan-400" />}
            {copiedGcode ? 'G-Code Copied!' : 'Copy CNC G-Code'}
          </button>

          <button
            onClick={handleDownloadCsv}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs transition"
          >
            <Download className="w-4 h-4" />
            Download Offsets CSV
          </button>
        </div>
      </div>

      {/* Radial Section Filter Pills */}
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-xs text-slate-400 font-bold mr-1">Filter Radial Section:</span>
        <button
          onClick={() => setSelectedRadialFilter('all')}
          className={`px-3 py-1 rounded-xl text-xs font-bold transition ${
            selectedRadialFilter === 'all'
              ? 'bg-cyan-500 text-slate-950'
              : 'bg-slate-950 text-slate-400 hover:text-white border border-slate-800'
          }`}
        >
          All Sections
        </button>
        {radialGeometry.map((sec) => (
          <button
            key={sec.rRatio}
            onClick={() => setSelectedRadialFilter(sec.rRatio)}
            className={`px-3 py-1 rounded-xl text-xs font-bold transition ${
              selectedRadialFilter === sec.rRatio
                ? 'bg-cyan-500 text-slate-950'
                : 'bg-slate-950 text-slate-400 hover:text-white border border-slate-800'
            }`}
          >
            r/R = {sec.rRatio}
          </button>
        ))}
      </div>

      {/* Offset Coordinates Data Table */}
      <div className="bg-slate-950 rounded-2xl border border-slate-800 overflow-x-auto max-h-[420px]">
        <table className="w-full text-left text-xs text-slate-300">
          <thead className="sticky top-0 bg-slate-900 text-cyan-400 font-bold text-[11px] uppercase tracking-wider border-b border-slate-800">
            <tr>
              <th className="p-3">Section (r/R)</th>
              <th className="p-3">Chord Position (%)</th>
              <th className="p-3">x (mm)</th>
              <th className="p-3">y Face (mm)</th>
              <th className="p-3">z Face (mm)</th>
              <th className="p-3">y Back (mm)</th>
              <th className="p-3">z Back (mm)</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60 font-mono">
            {filteredRows.map((row, idx) => (
              <tr key={idx} className="hover:bg-slate-900/60 transition">
                <td className="p-3 text-amber-400 font-bold">{row.rRatio.toFixed(2)}</td>
                <td className="p-3 text-slate-200">{row.chordPercent}%</td>
                <td className="p-3">{row.xMm}</td>
                <td className="p-3 text-emerald-400">{row.yFaceMm}</td>
                <td className="p-3 text-emerald-400">{row.zFaceMm}</td>
                <td className="p-3 text-cyan-400">{row.yBackMm}</td>
                <td className="p-3 text-cyan-400">{row.zBackMm}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
