import React, { useState, useEffect, useMemo } from 'react';
import { SubscriptionBanner } from './SubscriptionBanner';
import { PlanType } from '../types';
import {
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  ReferenceLine
} from 'recharts';
import {
  BookOpen,
  Search,
  Calculator,
  Check,
  Copy,
  Pin,
  PinOff,
  X,
  ChevronRight,
  Sliders,
  RotateCcw,
  Sparkles,
  Zap,
  Bookmark,
  Info,
  Layers,
  ArrowRight,
  PanelRightClose,
  PanelRightOpen,
  Filter,
  Activity,
  TrendingUp,
  BarChart2
} from 'lucide-react';

interface Props {
  userPlan?: PlanType;
  onOpenPricing?: (plan?: PlanType) => void;
}

export interface VariableDef {
  key: string;
  name: string;
  unit: string;
  defaultValue: number;
  min?: number;
  max?: number;
  step?: number;
  description?: string;
}

export interface FormulaDef {
  id: string;
  title: string;
  formula: string;
  category: 'Hydrostatics' | 'Ship Geometry' | 'Resistance & Propulsion' | 'Hydrodynamics' | 'Marine Machinery' | 'Structures & Waves' | 'Voyage Planning';
  description: string;
  variables: VariableDef[];
  calculate: (inputs: Record<string, number>) => { value: number; unit: string; note?: string; status?: 'pass' | 'warn' | 'info' };
  derivation?: string;
  standardRef?: string;
}

export const MARITIME_FORMULAS: FormulaDef[] = [
  {
    id: 'gm',
    title: 'Transverse Metacentric Height (GM)',
    formula: 'GM = KM - KG',
    category: 'Hydrostatics',
    description: 'Measures initial intact static stability. Indicates distance between gravity center G and transverse metacentre M.',
    standardRef: 'SOLAS Ch. II-1 & 2008 IS Code (Min GM ≥ 0.15 m)',
    derivation: 'Derived from hydrostatic stiffness matrix where GM = KB + BM - KG.',
    variables: [
      { key: 'KM', name: 'Metacentre Height above Keel (KM)', unit: 'm', defaultValue: 8.5, min: 1, max: 25, step: 0.1 },
      { key: 'KG', name: 'Vertical Center of Gravity (KG)', unit: 'm', defaultValue: 7.2, min: 0.5, max: 24, step: 0.1 }
    ],
    calculate: (inputs) => {
      const km = inputs.KM ?? 8.5;
      const kg = inputs.KG ?? 7.2;
      const gm = km - kg;
      const status = gm >= 0.15 ? 'pass' : 'warn';
      const note = gm >= 0.15
        ? 'SOLAS Compliant: Meets 2008 IS Code min 0.15 m threshold.'
        : 'CRITICAL WARNING: GM < 0.15 m violates SOLAS intact stability criteria!';
      return { value: Number(gm.toFixed(3)), unit: 'm', note, status };
    }
  },
  {
    id: 'cb',
    title: 'Block Coefficient (Cb)',
    formula: 'Cb = ∇ / (L * B * T)',
    category: 'Ship Geometry',
    description: 'Ratio of underwater displacement volume to the bounding box prism (L × B × T).',
    standardRef: 'ITTC Standard Ship Geometry & IMO Lines Model',
    derivation: 'Compares actual displacement volume to circumscribing rectangular block.',
    variables: [
      { key: 'Vol', name: 'Underwater Volume (∇)', unit: 'm³', defaultValue: 32000, min: 100, max: 300000, step: 100 },
      { key: 'L', name: 'Length Between Perpendiculars (Lbp)', unit: 'm', defaultValue: 180, min: 10, max: 400, step: 1 },
      { key: 'B', name: 'Moulded Beam (B)', unit: 'm', defaultValue: 28, min: 2, max: 70, step: 0.5 },
      { key: 'T', name: 'Moulded Draft (T)', unit: 'm', defaultValue: 9.5, min: 0.5, max: 25, step: 0.1 }
    ],
    calculate: (inputs) => {
      const vol = inputs.Vol ?? 32000;
      const l = inputs.L ?? 180;
      const b = inputs.B ?? 28;
      const t = inputs.T ?? 9.5;
      const cb = vol / (l * b * t);
      let note = 'Standard displacement vessel coefficient.';
      if (cb > 0.85) note = 'Full hull form (e.g. Tanker / Bulk Carrier). High wave resistance.';
      else if (cb < 0.65) note = 'Slender fine hull form (e.g. Container / Naval frigate). Fine entry.';
      return { value: Number(cb.toFixed(3)), unit: 'dim', note, status: cb > 0 && cb <= 1 ? 'pass' : 'warn' };
    }
  },
  {
    id: 'fn',
    title: 'Froude Number (Fn)',
    formula: 'Fn = V / √(g * L)',
    category: 'Hydrodynamics',
    description: 'Dimensionless ratio of inertial forces to gravitational wave resistance forces.',
    standardRef: 'ITTC Resistance Prediction & Model Scale Extrapolation',
    derivation: 'Governs dynamic surface wave patterns generated by moving ship hulls.',
    variables: [
      { key: 'V_kn', name: 'Service Speed (V)', unit: 'knots', defaultValue: 18.5, min: 1, max: 50, step: 0.5 },
      { key: 'L', name: 'Waterline Length (Lwl)', unit: 'm', defaultValue: 195, min: 5, max: 400, step: 1 }
    ],
    calculate: (inputs) => {
      const v_kn = inputs.V_kn ?? 18.5;
      const l = inputs.L ?? 195;
      const v_ms = v_kn * 0.514444;
      const fn = v_ms / Math.sqrt(9.81 * l);
      let note = 'Displacement regime (Fn < 0.4). Minimal wave resistance hump.';
      let status: 'pass' | 'warn' | 'info' = 'pass';
      if (fn >= 0.4 && fn < 0.8) {
        note = 'Semi-planing transition regime. High wave-making drag penalty.';
        status = 'warn';
      } else if (fn >= 0.8) {
        note = 'Full planing regime. Dynamic lift dominates hydrodynamics.';
        status = 'info';
      }
      return { value: Number(fn.toFixed(3)), unit: 'dim', note, status };
    }
  },
  {
    id: 'cadm',
    title: 'Admiralty Coefficient (C_adm)',
    formula: 'C_adm = (Δ^(2/3) * V³) / P_b',
    category: 'Resistance & Propulsion',
    description: 'Empirical power prediction formula for displacement ships comparing displacement, speed, and engine power.',
    standardRef: 'Clarksons Naval Architecture Power Benchmarks',
    derivation: 'Based on Froude scaling law assuming total resistance scales with wetted surface area.',
    variables: [
      { key: 'Displ', name: 'Displacement (Δ)', unit: 'MT', defaultValue: 38000, min: 500, max: 350000, step: 500 },
      { key: 'Speed', name: 'Service Speed (V)', unit: 'knots', defaultValue: 15.0, min: 5, max: 35, step: 0.5 },
      { key: 'Power', name: 'Brake Horsepower (Pb)', unit: 'kW', defaultValue: 10500, min: 500, max: 80000, step: 100 }
    ],
    calculate: (inputs) => {
      const displ = inputs.Displ ?? 38000;
      const speed = inputs.Speed ?? 15.0;
      const power = inputs.Power ?? 10500;
      const cadm = (Math.pow(displ, 2 / 3) * Math.pow(speed, 3)) / power;
      let note = 'High propulsive efficiency (C_adm > 400). Well-optimized hull & propeller.';
      let status: 'pass' | 'warn' | 'info' = 'pass';
      if (cadm < 280) {
        note = 'Low propulsive efficiency (C_adm < 280). High hull fouling or engine overload.';
        status = 'warn';
      } else if (cadm <= 400) {
        note = 'Average commercial efficiency range.';
        status = 'info';
      }
      return { value: Math.round(cadm), unit: 'coef', note, status };
    }
  },
  {
    id: 'sfoc',
    title: 'Specific Fuel Oil Consumption (SFOC)',
    formula: 'SFOC = (FuelMass * 10⁶) / (Power * 24)',
    category: 'Marine Machinery',
    description: 'Calculates fuel mass burned per unit of brake energy output in grams per kilowatt-hour.',
    standardRef: 'ISO 3046 / ISO 8178 Marine Diesel Testing',
    derivation: 'Normalizes daily HFO/MGO consumption to continuous engine load output.',
    variables: [
      { key: 'FuelMass', name: 'Daily Fuel Mass (M_f)', unit: 'MT/day', defaultValue: 32, min: 1, max: 250, step: 0.5 },
      { key: 'Power', name: 'Brake Power (Pb)', unit: 'kW', defaultValue: 7200, min: 200, max: 90000, step: 100 }
    ],
    calculate: (inputs) => {
      const fuelMass = inputs.FuelMass ?? 32;
      const power = inputs.Power ?? 7200;
      const sfoc = (fuelMass * 1000 * 1000) / (power * 24);
      let note = 'Optimal 2-stroke low-speed diesel engine efficiency (< 180 g/kWh).';
      let status: 'pass' | 'warn' | 'info' = 'pass';
      if (sfoc > 210) {
        note = 'High SFOC (> 210 g/kWh). Check fuel injector wear or turbocharger fouling.';
        status = 'warn';
      }
      return { value: Number(sfoc.toFixed(1)), unit: 'g/kWh', note, status };
    }
  },
  {
    id: 'bending_stress',
    title: 'Hull Girder Bending Stress (σ)',
    formula: 'σ = M_v / Z_deck',
    category: 'Structures & Waves',
    description: 'Calculates longitudinal deck bending stress under vertical wave bending moment.',
    standardRef: 'IACS UR S11 Structural Longitudinal Strength Criteria (Limit ≤ 175 MPa)',
    derivation: 'Euler-Bernoulli beam theory applied to ship hull girder cross section.',
    variables: [
      { key: 'Moment', name: 'Wave Bending Moment (M_v)', unit: 'MN·m', defaultValue: 1450, min: 50, max: 10000, step: 50 },
      { key: 'Modulus', name: 'Deck Section Modulus (Z_deck)', unit: 'm³', defaultValue: 12.5, min: 0.5, max: 80, step: 0.5 }
    ],
    calculate: (inputs) => {
      const moment = inputs.Moment ?? 1450;
      const modulus = inputs.Modulus ?? 12.5;
      const stress = moment / modulus; // MN/m² = MPa
      const status = stress <= 175 ? 'pass' : 'warn';
      const note = stress <= 175
        ? 'IACS S11 Safe: Hull deck stress within allowable 175 MPa yield envelope.'
        : 'HIGH STRUCTURAL RISK: Bending stress exceeds IACS 175 MPa limit!';
      return { value: Number(stress.toFixed(1)), unit: 'MPa', note, status };
    }
  },
  {
    id: 'cp',
    title: 'Prismatic Coefficient (Cp)',
    formula: 'Cp = ∇ / (Am * L)',
    category: 'Ship Geometry',
    description: 'Measures longitudinal volume distribution relative to midship cross-section area.',
    standardRef: 'Taylor-Gould Resistance Series Standards',
    derivation: 'Ratio of underwater volume to prism with midship section area Am and length L.',
    variables: [
      { key: 'Vol', name: 'Underwater Volume (∇)', unit: 'm³', defaultValue: 28500, min: 100, max: 250000, step: 100 },
      { key: 'Am', name: 'Midship Section Area (Am)', unit: 'm²', defaultValue: 215, min: 5, max: 1200, step: 5 },
      { key: 'L', name: 'Length Between Perpendiculars (L)', unit: 'm', defaultValue: 175, min: 10, max: 400, step: 1 }
    ],
    calculate: (inputs) => {
      const vol = inputs.Vol ?? 28500;
      const am = inputs.Am ?? 215;
      const l = inputs.L ?? 175;
      const cp = vol / (am * l);
      return {
        value: Number(cp.toFixed(3)),
        unit: 'dim',
        note: cp >= 0.55 && cp <= 0.85 ? 'Standard prismatic range for commercial vessels.' : 'Non-standard Cp.',
        status: cp >= 0.5 && cp <= 0.9 ? 'pass' : 'info'
      };
    }
  },
  {
    id: 'voyage_fuel',
    title: 'Estimated Voyage Fuel Consumption (FC)',
    formula: 'FC = (Dist / Speed) * (DailyFuel / 24)',
    category: 'Voyage Planning',
    description: 'Calculates total bunker fuel required for sea passage based on distance, speed, and daily rate.',
    standardRef: 'IMO CII Operational Fuel Oil Consumption Logging',
    derivation: 'Converts passage distance and service speed to steaming hours and multiplies by hourly fuel rate.',
    variables: [
      { key: 'Dist', name: 'Voyage Distance', unit: 'NM', defaultValue: 4200, min: 10, max: 25000, step: 50 },
      { key: 'Speed', name: 'Average Sea Speed', unit: 'knots', defaultValue: 14.5, min: 5, max: 35, step: 0.5 },
      { key: 'DailyFuel', name: 'Daily Fuel Rate', unit: 'MT/day', defaultValue: 28.5, min: 2, max: 200, step: 0.5 }
    ],
    calculate: (inputs) => {
      const dist = inputs.Dist ?? 4200;
      const speed = inputs.Speed ?? 14.5;
      const dailyFuel = inputs.DailyFuel ?? 28.5;
      const hours = dist / speed;
      const fc = (hours / 24) * dailyFuel;
      return {
        value: Number(fc.toFixed(1)),
        unit: 'MT',
        note: `Total passage duration: ${Math.round(hours)} hours (${(hours / 24).toFixed(1)} days steaming).`,
        status: 'info'
      };
    }
  }
];

interface ChartProps {
  formula: FormulaDef;
  currentInputs: Record<string, number>;
}

export const FormulaSensitivityChart: React.FC<ChartProps> = ({ formula, currentInputs }) => {
  const [selectedVarKey, setSelectedVarKey] = useState<string>(
    formula.variables[0]?.key || ''
  );

  useEffect(() => {
    if (!formula.variables.some((v) => v.key === selectedVarKey)) {
      setSelectedVarKey(formula.variables[0]?.key || '');
    }
  }, [formula, selectedVarKey]);

  const targetVar = formula.variables.find((v) => v.key === selectedVarKey) || formula.variables[0];
  const currentVal = currentInputs[targetVar?.key] ?? targetVar?.defaultValue ?? 0;

  const chartData = useMemo(() => {
    if (!targetVar) return [];
    const min = targetVar.min ?? Math.max(0, currentVal * 0.2);
    const max = targetVar.max ?? (currentVal === 0 ? 100 : currentVal * 2);
    const steps = 25;
    const stepSize = (max - min) / (steps - 1 || 1);

    const points = [];
    for (let i = 0; i < steps; i++) {
      const varVal = Number((min + i * stepSize).toFixed(2));
      const testInputs = { ...currentInputs, [targetVar.key]: varVal };
      const res = formula.calculate(testInputs);
      points.push({
        x: varVal,
        y: res.value,
        unit: res.unit,
        status: res.status
      });
    }
    return points;
  }, [formula, currentInputs, targetVar, currentVal]);

  const currentResult = useMemo(() => {
    return formula.calculate(currentInputs);
  }, [formula, currentInputs]);

  if (!targetVar) return null;

  return (
    <div className="space-y-2 bg-slate-950 p-3.5 rounded-2xl border border-slate-800/80 shadow-inner">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
        <div className="flex items-center gap-1.5 text-amber-300 font-extrabold">
          <Activity className="w-3.5 h-3.5 text-amber-400 shrink-0" />
          <span>Parameter Sensitivity Curve</span>
        </div>

        {/* Variable Selector Pills */}
        {formula.variables.length > 1 && (
          <div className="flex items-center gap-1 overflow-x-auto pb-1 sm:pb-0 scrollbar-none">
            <span className="text-[10px] text-slate-500 font-semibold mr-1 shrink-0">Sweep Var:</span>
            {formula.variables.map((v) => (
              <button
                key={v.key}
                onClick={() => setSelectedVarKey(v.key)}
                className={`px-2 py-0.5 rounded-md text-[10px] font-bold transition whitespace-nowrap ${
                  selectedVarKey === v.key
                    ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40 shadow-sm'
                    : 'bg-slate-900 text-slate-400 hover:text-slate-200 border border-slate-800'
                }`}
              >
                {v.key}
              </button>
            ))}
          </div>
        )}
      </div>

      <div className="text-[11px] text-slate-400 flex items-center justify-between flex-wrap gap-1">
        <span>
          Sweeping <strong className="text-slate-200 font-bold">{targetVar.name} ({targetVar.key})</strong>
        </span>
        <span className="text-sky-400 font-mono font-bold text-[10px]">
          Current Point: {currentVal} {targetVar.unit}
        </span>
      </div>

      <div className="h-44 w-full pt-1">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={chartData} margin={{ top: 10, right: 15, left: -20, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
            <XAxis
              dataKey="x"
              stroke="#64748b"
              fontSize={10}
              tickFormatter={(val) => `${val}`}
            />
            <YAxis
              stroke="#64748b"
              fontSize={10}
              domain={['auto', 'auto']}
            />
            <Tooltip
              content={({ active, payload }) => {
                if (active && payload && payload.length) {
                  const data = payload[0].payload;
                  return (
                    <div className="bg-slate-900 border border-slate-700 p-2.5 rounded-xl shadow-xl text-xs space-y-1">
                      <p className="text-slate-400 font-medium">
                        {targetVar.name}: <span className="text-white font-bold">{data.x} {targetVar.unit}</span>
                      </p>
                      <p className="text-amber-300 font-bold font-mono">
                        Output: {data.y} {data.unit}
                      </p>
                    </div>
                  );
                }
                return null;
              }}
            />
            <Line
              type="monotone"
              dataKey="y"
              stroke="#f59e0b"
              strokeWidth={2.5}
              dot={false}
              activeDot={{ r: 5, fill: '#f59e0b', stroke: '#fff' }}
            />
            <ReferenceLine
              x={currentVal}
              stroke="#38bdf8"
              strokeDasharray="4 4"
              strokeWidth={2}
              label={{
                value: `Current: ${currentResult.value}`,
                fill: '#38bdf8',
                fontSize: 10,
                position: 'top',
              }}
            />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
};

export const MaritimeFormulaLibraryView: React.FC<Props> = ({ userPlan = 'student', onOpenPricing }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  
  // Quick-Reference Pinned Formula IDs (defaults to GM, Cb, Fn)
  const [pinnedIds, setPinnedIds] = useState<string[]>(() => {
    try {
      const saved = localStorage.getItem('maritime_pinned_formulas');
      return saved ? JSON.parse(saved) : ['gm', 'cb', 'fn'];
    } catch {
      return ['gm', 'cb', 'fn'];
    }
  });

  // Floating Quick-Reference Panel open state
  const [isPanelOpen, setIsPanelOpen] = useState(false);
  const [activeFormulaId, setActiveFormulaId] = useState<string>('gm');

  // Interactive inputs state for formulas
  const [formulaInputs, setFormulaInputs] = useState<Record<string, Record<string, number>>>(() => {
    const init: Record<string, Record<string, number>> = {};
    MARITIME_FORMULAS.forEach((f) => {
      init[f.id] = {};
      f.variables.forEach((v) => {
        init[f.id][v.key] = v.defaultValue;
      });
    });
    return init;
  });

  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Sync pinnedIds to localStorage
  useEffect(() => {
    try {
      localStorage.setItem('maritime_pinned_formulas', JSON.stringify(pinnedIds));
    } catch (e) {
      console.warn('Failed to save pinned formulas:', e);
    }
  }, [pinnedIds]);

  const togglePin = (id: string, e?: React.MouseEvent) => {
    e?.stopPropagation();
    setPinnedIds((prev) => {
      if (prev.includes(id)) {
        return prev.filter((p) => p !== id);
      } else {
        return [...prev, id];
      }
    });
  };

  const handleInputChange = (formulaId: string, varKey: string, val: number) => {
    setFormulaInputs((prev) => ({
      ...prev,
      [formulaId]: {
        ...prev[formulaId],
        [varKey]: val
      }
    }));
  };

  const resetFormulaInputs = (formulaId: string) => {
    const target = MARITIME_FORMULAS.find((f) => f.id === formulaId);
    if (!target) return;
    const defaults: Record<string, number> = {};
    target.variables.forEach((v) => {
      defaults[v.key] = v.defaultValue;
    });
    setFormulaInputs((prev) => ({
      ...prev,
      [formulaId]: defaults
    }));
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const categories = ['All', 'Hydrostatics', 'Ship Geometry', 'Resistance & Propulsion', 'Hydrodynamics', 'Marine Machinery', 'Structures & Waves', 'Voyage Planning'];

  const filteredFormulas = useMemo(() => {
    return MARITIME_FORMULAS.filter((f) => {
      const matchesCat = selectedCategory === 'All' || f.category === selectedCategory;
      const matchesSearch =
        f.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        f.formula.toLowerCase().includes(searchTerm.toLowerCase()) ||
        f.category.toLowerCase().includes(searchTerm.toLowerCase()) ||
        f.description.toLowerCase().includes(searchTerm.toLowerCase());
      return matchesCat && matchesSearch;
    });
  }, [searchTerm, selectedCategory]);

  // Pinned formulas objects
  const pinnedFormulas = useMemo(() => {
    return MARITIME_FORMULAS.filter((f) => pinnedIds.includes(f.id));
  }, [pinnedIds]);

  const activeFormula = useMemo(() => {
    return MARITIME_FORMULAS.find((f) => f.id === activeFormulaId) || MARITIME_FORMULAS[0];
  }, [activeFormulaId]);

  return (
    <div className="relative max-w-7xl mx-auto px-4 py-8 space-y-6 text-slate-100 min-h-screen">
      <SubscriptionBanner userPlan={userPlan} onOpenPricing={onOpenPricing} featureName="Maritime Formula Library" />

      {/* Header Banner */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-gradient-to-br from-slate-900 via-slate-900 to-amber-950/30 p-6 sm:p-8 rounded-3xl border border-slate-800 shadow-xl">
        <div className="space-y-2">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 text-xs font-extrabold border border-amber-500/30 flex items-center gap-1">
              <Zap className="w-3.5 h-3.5 text-amber-400" /> Tool #54
            </span>
            <span className="px-3 py-1 rounded-full bg-sky-500/20 text-sky-300 text-xs font-bold border border-sky-500/30">
              Interactive Equation Solvers
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl lg:text-4xl font-black text-white flex items-center gap-3">
            <BookOpen className="w-8 h-8 text-amber-400 shrink-0" />
            Maritime & Naval Architecture Formula Library
          </h1>
          <p className="text-slate-300 text-sm max-w-3xl leading-relaxed">
            Comprehensive reference database for hydrostatics, ship resistance, propulsion, marine machinery, and structural engineering equations. Pin formulas to the <strong>Floating Quick-Reference Panel</strong> for instant calculation side-by-side.
          </p>
        </div>

        {/* Trigger for Floating Quick Reference Side Panel */}
        <button
          onClick={() => {
            setIsPanelOpen(true);
            if (!pinnedIds.includes(activeFormulaId) && pinnedIds.length > 0) {
              setActiveFormulaId(pinnedIds[0]);
            }
          }}
          className="shrink-0 inline-flex items-center gap-2.5 px-5 py-3 rounded-2xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-slate-950 font-black text-xs sm:text-sm shadow-lg shadow-amber-500/20 hover:scale-[1.02] active:scale-95 transition-all cursor-pointer"
        >
          <Bookmark className="w-4 h-4 fill-slate-950" />
          Quick-Reference Side Panel
          {pinnedIds.length > 0 && (
            <span className="px-2 py-0.5 rounded-full bg-slate-950 text-amber-300 text-xs font-black">
              {pinnedIds.length}
            </span>
          )}
        </button>
      </div>

      {/* Category Pills & Search Controls */}
      <div className="space-y-4 bg-slate-900/60 p-4 sm:p-5 rounded-3xl border border-slate-800/80 backdrop-blur-md">
        <div className="flex flex-col md:flex-row gap-3 items-stretch md:items-center justify-between">
          {/* Search Box */}
          <div className="relative flex-1">
            <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-3.5" />
            <input
              type="text"
              placeholder="Search formulas by title, equation (e.g. GM = KM - KG), or category..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-10 py-2.5 bg-slate-950 border border-slate-800 rounded-2xl text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-500/80 transition"
            />
            {searchTerm && (
              <button
                onClick={() => setSearchTerm('')}
                className="absolute right-3 top-3 text-slate-500 hover:text-white"
              >
                <X className="w-4 h-4" />
              </button>
            )}
          </div>

          <div className="flex items-center gap-2 text-xs font-bold text-slate-400">
            <Filter className="w-3.5 h-3.5 text-amber-400" />
            Showing {filteredFormulas.length} of {MARITIME_FORMULAS.length} equations
          </div>
        </div>

        {/* Category Filters */}
        <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-thin">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition whitespace-nowrap ${
                selectedCategory === cat
                  ? 'bg-amber-500 text-slate-950 shadow-md shadow-amber-500/20'
                  : 'bg-slate-950 text-slate-400 hover:text-white hover:bg-slate-800 border border-slate-800'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Grid of Main Formulas Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {filteredFormulas.map((item) => {
          const isPinned = pinnedIds.includes(item.id);
          const currentInputs = formulaInputs[item.id] || {};
          const result = item.calculate(currentInputs);

          return (
            <div
              key={item.id}
              className={`relative bg-slate-900/90 rounded-3xl border transition-all duration-200 flex flex-col justify-between overflow-hidden group ${
                isPinned
                  ? 'border-amber-500/50 shadow-lg shadow-amber-500/5'
                  : 'border-slate-800 hover:border-slate-700'
              }`}
            >
              {/* Card Header */}
              <div className="p-5 space-y-3 border-b border-slate-800/80 bg-gradient-to-b from-slate-900 via-slate-900 to-slate-950/60">
                <div className="flex items-start justify-between gap-3">
                  <div className="space-y-1">
                    <span className="inline-block px-2.5 py-0.5 rounded-full bg-amber-500/10 text-amber-300 text-[10px] font-extrabold border border-amber-500/20">
                      {item.category}
                    </span>
                    <h3 className="font-extrabold text-base text-white group-hover:text-amber-300 transition-colors">
                      {item.title}
                    </h3>
                  </div>

                  {/* Pin / Unpin Button */}
                  <button
                    onClick={(e) => togglePin(item.id, e)}
                    className={`p-2 rounded-xl border transition-all ${
                      isPinned
                        ? 'bg-amber-500/20 border-amber-500/50 text-amber-300 hover:bg-amber-500/30'
                        : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-white hover:border-slate-700'
                    }`}
                    title={isPinned ? 'Unpin from Quick-Reference' : 'Pin to Quick-Reference Panel'}
                  >
                    <Pin className={`w-4 h-4 ${isPinned ? 'fill-amber-300 rotate-45' : ''}`} />
                  </button>
                </div>

                {/* Formula Expression Box */}
                <div className="relative flex items-center justify-between bg-slate-950 p-3.5 rounded-2xl border border-slate-800/80 group/code">
                  <code className="font-mono text-amber-300 text-sm sm:text-base font-black tracking-wide">
                    {item.formula}
                  </code>
                  <button
                    onClick={() => copyToClipboard(item.formula, item.id)}
                    className="p-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white text-xs flex items-center gap-1 transition"
                    title="Copy equation string"
                  >
                    {copiedId === item.id ? (
                      <Check className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <Copy className="w-3.5 h-3.5" />
                    )}
                  </button>
                </div>

                <p className="text-xs text-slate-300 leading-relaxed">{item.description}</p>
                {item.standardRef && (
                  <div className="flex items-center gap-1.5 text-[11px] text-sky-400 font-semibold pt-1">
                    <Info className="w-3.5 h-3.5 text-sky-400 shrink-0" />
                    {item.standardRef}
                  </div>
                )}
              </div>

              {/* Card Body - In-line Interactive Solver */}
              <div className="p-5 bg-slate-950/80 space-y-4">
                <div className="flex items-center justify-between text-xs font-bold text-slate-400">
                  <span className="flex items-center gap-1.5 text-slate-300">
                    <Sliders className="w-3.5 h-3.5 text-amber-400" /> Live Equation Inputs
                  </span>
                  <button
                    onClick={() => resetFormulaInputs(item.id)}
                    className="text-[11px] text-slate-400 hover:text-slate-200 flex items-center gap-1"
                  >
                    <RotateCcw className="w-3 h-3" /> Reset
                  </button>
                </div>

                {/* Input Fields */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {item.variables.map((v) => {
                    const val = currentInputs[v.key] ?? v.defaultValue;
                    return (
                      <div key={v.key} className="space-y-1 bg-slate-900/80 p-2.5 rounded-xl border border-slate-800">
                        <div className="flex items-center justify-between text-[11px]">
                          <span className="text-slate-300 font-medium truncate">{v.name}</span>
                          <span className="text-amber-400 font-bold ml-1">{v.unit}</span>
                        </div>
                        <input
                          type="number"
                          value={val}
                          step={v.step || 0.1}
                          min={v.min}
                          max={v.max}
                          onChange={(e) => handleInputChange(item.id, v.key, parseFloat(e.target.value) || 0)}
                          className="w-full bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1 text-xs text-white font-mono focus:outline-none focus:border-amber-500"
                        />
                      </div>
                    );
                  })}
                </div>

                {/* Computed Output Box */}
                <div className="p-3.5 rounded-2xl bg-slate-900 border border-slate-800 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-extrabold uppercase tracking-wider text-slate-400">
                      Computed Result
                    </span>
                    <span
                      className={`text-[10px] font-extrabold px-2 py-0.5 rounded-full border ${
                        result.status === 'pass'
                          ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30'
                          : result.status === 'warn'
                          ? 'bg-rose-500/20 text-rose-300 border-rose-500/30'
                          : 'bg-sky-500/20 text-sky-300 border-sky-500/30'
                      }`}
                    >
                      {result.status === 'pass' ? 'PASSED' : result.status === 'warn' ? 'WARNING' : 'INFO'}
                    </span>
                  </div>

                  <div className="flex items-baseline gap-2">
                    <span className="text-2xl font-black font-mono text-amber-300">
                      {result.value}
                    </span>
                    <span className="text-sm font-bold text-slate-400">{result.unit}</span>
                  </div>

                  {result.note && (
                    <p className="text-[11px] text-slate-300 leading-normal pt-1 border-t border-slate-800/60">
                      {result.note}
                    </p>
                  )}
                </div>

                {/* Sensitivity Plot Chart */}
                <FormulaSensitivityChart formula={item} currentInputs={currentInputs} />

                {/* Open in Floating Panel Action */}
                <div className="flex items-center justify-between pt-1">
                  <button
                    onClick={() => {
                      if (!isPinned) togglePin(item.id);
                      setActiveFormulaId(item.id);
                      setIsPanelOpen(true);
                    }}
                    className="text-xs font-bold text-sky-400 hover:text-sky-300 flex items-center gap-1 transition"
                  >
                    Open in Side Panel <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Floating Quick Reference Button (Fixed Bottom-Right Badge) */}
      <div className="fixed bottom-6 right-6 z-40">
        <button
          onClick={() => setIsPanelOpen(true)}
          className="flex items-center gap-2.5 px-4 py-3 rounded-2xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-black text-xs sm:text-sm shadow-2xl shadow-amber-500/30 ring-4 ring-slate-950 transition-all hover:scale-105 active:scale-95 cursor-pointer"
        >
          <Pin className="w-4 h-4 fill-slate-950" />
          <span>Quick Reference</span>
          {pinnedIds.length > 0 && (
            <span className="px-2 py-0.5 rounded-full bg-slate-950 text-amber-300 text-xs font-black">
              {pinnedIds.length}
            </span>
          )}
        </button>
      </div>

      {/* Floating Quick-Reference Side Modal / Drawer */}
      {isPanelOpen && (
        <div className="fixed inset-0 z-50 flex justify-end">
          {/* Backdrop overlay */}
          <div
            onClick={() => setIsPanelOpen(false)}
            className="absolute inset-0 bg-slate-950/70 backdrop-blur-sm animate-in fade-in duration-200"
          />

          {/* Drawer Content */}
          <div className="relative w-full max-w-lg bg-slate-900 border-l border-slate-800 text-slate-100 h-full flex flex-col shadow-2xl z-10 animate-in slide-in-from-right duration-250">
            {/* Drawer Header */}
            <div className="p-5 border-b border-slate-800 bg-slate-950/80 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="p-2 rounded-xl bg-amber-500/20 border border-amber-500/30">
                  <Bookmark className="w-5 h-5 text-amber-400" />
                </div>
                <div>
                  <h2 className="font-black text-base text-white">Floating Quick-Reference</h2>
                  <p className="text-xs text-slate-400">Pinned Maritime Engineering Equations</p>
                </div>
              </div>

              <button
                onClick={() => setIsPanelOpen(false)}
                className="p-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white transition"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Pinned Selector Bar */}
            <div className="p-4 bg-slate-950/50 border-b border-slate-800/80 space-y-3">
              <div className="flex items-center justify-between text-xs font-bold text-slate-400">
                <span>Pinned Equations ({pinnedFormulas.length})</span>
                {pinnedIds.length > 0 && (
                  <button
                    onClick={() => setPinnedIds([])}
                    className="text-[11px] text-rose-400 hover:underline"
                  >
                    Unpin All
                  </button>
                )}
              </div>

              {/* Pinned Chips */}
              <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-thin">
                {pinnedFormulas.map((f) => {
                  const isActive = f.id === activeFormulaId;
                  return (
                    <button
                      key={f.id}
                      onClick={() => setActiveFormulaId(f.id)}
                      className={`px-3 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 shrink-0 ${
                        isActive
                          ? 'bg-amber-500 text-slate-950 shadow-md shadow-amber-500/20'
                          : 'bg-slate-900 text-slate-300 hover:bg-slate-800 border border-slate-800'
                      }`}
                    >
                      <span className="truncate max-w-[120px]">{f.title}</span>
                      <span
                        onClick={(e) => togglePin(f.id, e)}
                        className={`p-0.5 rounded hover:bg-black/20 ${isActive ? 'text-slate-950' : 'text-slate-400'}`}
                        title="Unpin"
                      >
                        <X className="w-3 h-3" />
                      </span>
                    </button>
                  );
                })}

                {pinnedFormulas.length === 0 && (
                  <p className="text-xs text-slate-500 italic py-1">No formulas pinned yet. Select an equation below.</p>
                )}
              </div>

              {/* Quick Dropdown to Add Equation */}
              <div className="pt-1">
                <select
                  value=""
                  onChange={(e) => {
                    if (e.target.value) {
                      if (!pinnedIds.includes(e.target.value)) {
                        togglePin(e.target.value);
                      }
                      setActiveFormulaId(e.target.value);
                    }
                  }}
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-xs text-slate-300 focus:outline-none focus:border-amber-500"
                >
                  <option value="" disabled>
                    + Pin another formula from database...
                  </option>
                  {MARITIME_FORMULAS.map((f) => (
                    <option key={f.id} value={f.id}>
                      {pinnedIds.includes(f.id) ? '📌 ' : ''} {f.title} ({f.category})
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Active Formula Calculation Area */}
            <div className="flex-1 overflow-y-auto p-5 space-y-5">
              {activeFormula ? (
                <div className="space-y-4">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <span className="px-2.5 py-0.5 rounded-full bg-amber-500/10 text-amber-300 text-[10px] font-extrabold border border-amber-500/20">
                        {activeFormula.category}
                      </span>
                      <h3 className="font-extrabold text-lg text-white mt-1">{activeFormula.title}</h3>
                    </div>

                    <button
                      onClick={() => togglePin(activeFormula.id)}
                      className="p-2 rounded-xl bg-slate-800 text-amber-300 hover:bg-slate-700 transition shrink-0"
                      title="Unpin formula"
                    >
                      <Pin className="w-4 h-4 fill-amber-300 rotate-45" />
                    </button>
                  </div>

                  {/* Expression */}
                  <div className="bg-slate-950 p-4 rounded-2xl border border-slate-800 font-mono text-amber-300 text-center text-lg font-black tracking-wide">
                    {activeFormula.formula}
                  </div>

                  <p className="text-xs text-slate-300">{activeFormula.description}</p>

                  {/* Calculator Inputs */}
                  <div className="p-4 rounded-2xl bg-slate-950/80 border border-slate-800/80 space-y-3">
                    <div className="flex items-center justify-between text-xs font-extrabold text-slate-300">
                      <span className="flex items-center gap-1.5">
                        <Sliders className="w-4 h-4 text-amber-400" /> Adjust Variables
                      </span>
                      <button
                        onClick={() => resetFormulaInputs(activeFormula.id)}
                        className="text-[11px] text-slate-400 hover:text-white flex items-center gap-1"
                      >
                        <RotateCcw className="w-3 h-3" /> Reset Defaults
                      </button>
                    </div>

                    <div className="space-y-3">
                      {activeFormula.variables.map((v) => {
                        const val = formulaInputs[activeFormula.id]?.[v.key] ?? v.defaultValue;
                        return (
                          <div key={v.key} className="space-y-1 bg-slate-900 p-3 rounded-xl border border-slate-800">
                            <div className="flex items-center justify-between text-xs">
                              <span className="font-bold text-slate-200">{v.name}</span>
                              <span className="text-amber-400 font-mono font-bold">{v.unit}</span>
                            </div>

                            <div className="flex items-center gap-3">
                              <input
                                type="number"
                                value={val}
                                step={v.step || 0.1}
                                min={v.min}
                                max={v.max}
                                onChange={(e) =>
                                  handleInputChange(activeFormula.id, v.key, parseFloat(e.target.value) || 0)
                                }
                                className="w-28 bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1 text-xs font-mono text-white focus:outline-none focus:border-amber-500"
                              />
                              <input
                                type="range"
                                min={v.min ?? 0}
                                max={v.max ?? 100}
                                step={v.step ?? 0.1}
                                value={val}
                                onChange={(e) =>
                                  handleInputChange(activeFormula.id, v.key, parseFloat(e.target.value) || 0)
                                }
                                className="flex-1 accent-amber-500 h-1.5 bg-slate-950 rounded-lg appearance-none cursor-pointer"
                              />
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                  {/* Calculated Output */}
                  {(() => {
                    const res = activeFormula.calculate(formulaInputs[activeFormula.id] || {});
                    return (
                      <div className="p-4 rounded-2xl bg-gradient-to-br from-slate-950 to-slate-900 border border-slate-800 space-y-2">
                        <div className="flex items-center justify-between">
                          <span className="text-xs font-black text-slate-400 uppercase tracking-wider">
                            Live Result
                          </span>
                          <span
                            className={`text-[10px] font-extrabold px-2.5 py-0.5 rounded-full border ${
                              res.status === 'pass'
                                ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30'
                                : res.status === 'warn'
                                ? 'bg-rose-500/20 text-rose-300 border-rose-500/30'
                                : 'bg-sky-500/20 text-sky-300 border-sky-500/30'
                            }`}
                          >
                            {res.status === 'pass' ? 'SOLAS / PASS' : res.status === 'warn' ? 'WARNING' : 'CALCULATED'}
                          </span>
                        </div>

                        <div className="flex items-baseline gap-2">
                          <span className="text-3xl font-black font-mono text-amber-300">{res.value}</span>
                          <span className="text-base font-bold text-slate-400">{res.unit}</span>
                        </div>

                        {res.note && (
                          <p className="text-xs text-slate-300 leading-normal pt-2 border-t border-slate-800">
                            {res.note}
                          </p>
                        )}
                      </div>
                    );
                  })()}

                  {/* Drawer Sensitivity Chart */}
                  <FormulaSensitivityChart
                    formula={activeFormula}
                    currentInputs={formulaInputs[activeFormula.id] || {}}
                  />

                  {activeFormula.derivation && (
                    <div className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800/80 text-xs text-slate-400 space-y-1">
                      <span className="font-extrabold text-slate-300 block">Engineering Derivation:</span>
                      <p>{activeFormula.derivation}</p>
                    </div>
                  )}
                </div>
              ) : (
                <div className="p-8 text-center text-slate-400 space-y-2">
                  <Bookmark className="w-8 h-8 text-slate-600 mx-auto" />
                  <p>Select a pinned formula above to start calculating.</p>
                </div>
              )}
            </div>

            {/* Drawer Footer */}
            <div className="p-4 border-t border-slate-800 bg-slate-950 flex items-center justify-between text-xs text-slate-400">
              <span>{pinnedIds.length} Pinned Equations</span>
              <button
                onClick={() => setIsPanelOpen(false)}
                className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold transition"
              >
                Close Side Panel
              </button>
            </div>
          </div>
        </div>
      )}

      <SubscriptionBanner userPlan={userPlan} onOpenPricing={onOpenPricing} compact />
    </div>
  );
};
